#: fonts {{{
font_family JetBrains Mono Nerd Font
font_size 12.0
#: }}}

#: colors {{{
# Exported from https://paletty.dev

foreground #fdf3fa
background #222422
cursor #b9b1c0
cursor_text_color #0f0c0b
selection_foreground #6b5754
selection_background #cee8e3

color0 #151629
color1 #e86a7b
color2 #17e617
color3 #e7e91e
color4 #7375e4
color5 #ee20d5
color6 #19d9e2
color7 #e6ddc7
color8 #767c86
color9 #eac096
color10 #d2e9c1
color11 #d7e9a2
color12 #c1c8ea
color13 #ebc4ea
color14 #aeecdc
color15 #cde7f1


background_opacity 0.9
#: }}}

#: window layout {{{
window_padding_width 6
#: }}}
